---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: check
        name: Cargo Check
        entry: cargo fmt --manifest-path 2024/Cargo.toml
        language: system
        types: ['rust']
        pass_filenames: false
